# coding: utf-8

"""
    TrackingAPI

    API for retrieving tracking data and changing settings on LightBug & RemoteThings tracking devices  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from lb_tracking_api.configuration import Configuration


class Device(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'imei': 'str',
        'iccid': 'str',
        'lora_id': 'float',
        'imsi': 'str',
        'bt_mac': 'float',
        'bt_mac_address': 'str',
        'uwb_id': 'float',
        'serial': 'str',
        'type': 'str',
        'expires': 'datetime',
        'last_connection': 'datetime',
        'first_seen': 'datetime',
        'mode': 'str',
        'name': 'str',
        'battery_voltage': 'float',
        'battery_pct': 'float',
        'battery_type': 'str',
        'tags': 'list[str]',
        'current_mode': 'float',
        'color': 'str',
        'save_to_web': 'bool',
        'active': 'bool',
        'deep_sleep': 'bool',
        'simstate': 'str',
        'stripe_subscription': 'str',
        'subscription_type': 'str',
        'meta': 'object',
        'reseller_id': 'float',
        'reseller_plan_id': 'float',
        'bt_passkey': 'float',
        'id': 'float',
        'owner_id': 'float',
        'secure_phone_id': 'float'
    }

    attribute_map = {
        'imei': 'imei',
        'iccid': 'iccid',
        'lora_id': 'loraId',
        'imsi': 'imsi',
        'bt_mac': 'btMac',
        'bt_mac_address': 'btMacAddress',
        'uwb_id': 'uwbId',
        'serial': 'serial',
        'type': 'type',
        'expires': 'expires',
        'last_connection': 'lastConnection',
        'first_seen': 'firstSeen',
        'mode': 'mode',
        'name': 'name',
        'battery_voltage': 'batteryVoltage',
        'battery_pct': 'batteryPct',
        'battery_type': 'batteryType',
        'tags': 'tags',
        'current_mode': 'currentMode',
        'color': 'color',
        'save_to_web': 'saveToWeb',
        'active': 'active',
        'deep_sleep': 'deepSleep',
        'simstate': 'simstate',
        'stripe_subscription': 'stripeSubscription',
        'subscription_type': 'subscriptionType',
        'meta': 'meta',
        'reseller_id': 'resellerId',
        'reseller_plan_id': 'resellerPlanId',
        'bt_passkey': 'btPasskey',
        'id': 'id',
        'owner_id': 'ownerId',
        'secure_phone_id': 'securePhoneId'
    }

    def __init__(self, imei=None, iccid=None, lora_id=None, imsi=None, bt_mac=None, bt_mac_address=None, uwb_id=None, serial=None, type=None, expires=None, last_connection=None, first_seen=None, mode='default', name=None, battery_voltage=None, battery_pct=None, battery_type='LIO', tags=None, current_mode=None, color='fc7c3d', save_to_web=False, active=False, deep_sleep=False, simstate='active', stripe_subscription=None, subscription_type=None, meta=None, reseller_id=None, reseller_plan_id=None, bt_passkey=None, id=None, owner_id=None, secure_phone_id=None, _configuration=None):  # noqa: E501
        """Device - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._imei = None
        self._iccid = None
        self._lora_id = None
        self._imsi = None
        self._bt_mac = None
        self._bt_mac_address = None
        self._uwb_id = None
        self._serial = None
        self._type = None
        self._expires = None
        self._last_connection = None
        self._first_seen = None
        self._mode = None
        self._name = None
        self._battery_voltage = None
        self._battery_pct = None
        self._battery_type = None
        self._tags = None
        self._current_mode = None
        self._color = None
        self._save_to_web = None
        self._active = None
        self._deep_sleep = None
        self._simstate = None
        self._stripe_subscription = None
        self._subscription_type = None
        self._meta = None
        self._reseller_id = None
        self._reseller_plan_id = None
        self._bt_passkey = None
        self._id = None
        self._owner_id = None
        self._secure_phone_id = None
        self.discriminator = None

        if imei is not None:
            self.imei = imei
        if iccid is not None:
            self.iccid = iccid
        if lora_id is not None:
            self.lora_id = lora_id
        if imsi is not None:
            self.imsi = imsi
        if bt_mac is not None:
            self.bt_mac = bt_mac
        if bt_mac_address is not None:
            self.bt_mac_address = bt_mac_address
        if uwb_id is not None:
            self.uwb_id = uwb_id
        if serial is not None:
            self.serial = serial
        if type is not None:
            self.type = type
        if expires is not None:
            self.expires = expires
        if last_connection is not None:
            self.last_connection = last_connection
        self.first_seen = first_seen
        if mode is not None:
            self.mode = mode
        if name is not None:
            self.name = name
        if battery_voltage is not None:
            self.battery_voltage = battery_voltage
        if battery_pct is not None:
            self.battery_pct = battery_pct
        if battery_type is not None:
            self.battery_type = battery_type
        if tags is not None:
            self.tags = tags
        if current_mode is not None:
            self.current_mode = current_mode
        if color is not None:
            self.color = color
        if save_to_web is not None:
            self.save_to_web = save_to_web
        if active is not None:
            self.active = active
        if deep_sleep is not None:
            self.deep_sleep = deep_sleep
        if simstate is not None:
            self.simstate = simstate
        if stripe_subscription is not None:
            self.stripe_subscription = stripe_subscription
        if subscription_type is not None:
            self.subscription_type = subscription_type
        if meta is not None:
            self.meta = meta
        if reseller_id is not None:
            self.reseller_id = reseller_id
        if reseller_plan_id is not None:
            self.reseller_plan_id = reseller_plan_id
        if bt_passkey is not None:
            self.bt_passkey = bt_passkey
        if id is not None:
            self.id = id
        if owner_id is not None:
            self.owner_id = owner_id
        if secure_phone_id is not None:
            self.secure_phone_id = secure_phone_id

    @property
    def imei(self):
        """Gets the imei of this Device.  # noqa: E501


        :return: The imei of this Device.  # noqa: E501
        :rtype: str
        """
        return self._imei

    @imei.setter
    def imei(self, imei):
        """Sets the imei of this Device.


        :param imei: The imei of this Device.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                imei is not None and len(imei) > 15):
            raise ValueError("Invalid value for `imei`, length must be less than or equal to `15`")  # noqa: E501

        self._imei = imei

    @property
    def iccid(self):
        """Gets the iccid of this Device.  # noqa: E501


        :return: The iccid of this Device.  # noqa: E501
        :rtype: str
        """
        return self._iccid

    @iccid.setter
    def iccid(self, iccid):
        """Sets the iccid of this Device.


        :param iccid: The iccid of this Device.  # noqa: E501
        :type: str
        """

        self._iccid = iccid

    @property
    def lora_id(self):
        """Gets the lora_id of this Device.  # noqa: E501


        :return: The lora_id of this Device.  # noqa: E501
        :rtype: float
        """
        return self._lora_id

    @lora_id.setter
    def lora_id(self, lora_id):
        """Sets the lora_id of this Device.


        :param lora_id: The lora_id of this Device.  # noqa: E501
        :type: float
        """

        self._lora_id = lora_id

    @property
    def imsi(self):
        """Gets the imsi of this Device.  # noqa: E501


        :return: The imsi of this Device.  # noqa: E501
        :rtype: str
        """
        return self._imsi

    @imsi.setter
    def imsi(self, imsi):
        """Sets the imsi of this Device.


        :param imsi: The imsi of this Device.  # noqa: E501
        :type: str
        """

        self._imsi = imsi

    @property
    def bt_mac(self):
        """Gets the bt_mac of this Device.  # noqa: E501

        Bluetooth MAC Address as 48bit number  # noqa: E501

        :return: The bt_mac of this Device.  # noqa: E501
        :rtype: float
        """
        return self._bt_mac

    @bt_mac.setter
    def bt_mac(self, bt_mac):
        """Sets the bt_mac of this Device.

        Bluetooth MAC Address as 48bit number  # noqa: E501

        :param bt_mac: The bt_mac of this Device.  # noqa: E501
        :type: float
        """

        self._bt_mac = bt_mac

    @property
    def bt_mac_address(self):
        """Gets the bt_mac_address of this Device.  # noqa: E501

        Bluetooth MAC Address in standard format  # noqa: E501

        :return: The bt_mac_address of this Device.  # noqa: E501
        :rtype: str
        """
        return self._bt_mac_address

    @bt_mac_address.setter
    def bt_mac_address(self, bt_mac_address):
        """Sets the bt_mac_address of this Device.

        Bluetooth MAC Address in standard format  # noqa: E501

        :param bt_mac_address: The bt_mac_address of this Device.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                bt_mac_address is not None and len(bt_mac_address) > 17):
            raise ValueError("Invalid value for `bt_mac_address`, length must be less than or equal to `17`")  # noqa: E501

        self._bt_mac_address = bt_mac_address

    @property
    def uwb_id(self):
        """Gets the uwb_id of this Device.  # noqa: E501

        UWB Address as 32bit number  # noqa: E501

        :return: The uwb_id of this Device.  # noqa: E501
        :rtype: float
        """
        return self._uwb_id

    @uwb_id.setter
    def uwb_id(self, uwb_id):
        """Sets the uwb_id of this Device.

        UWB Address as 32bit number  # noqa: E501

        :param uwb_id: The uwb_id of this Device.  # noqa: E501
        :type: float
        """

        self._uwb_id = uwb_id

    @property
    def serial(self):
        """Gets the serial of this Device.  # noqa: E501


        :return: The serial of this Device.  # noqa: E501
        :rtype: str
        """
        return self._serial

    @serial.setter
    def serial(self, serial):
        """Sets the serial of this Device.


        :param serial: The serial of this Device.  # noqa: E501
        :type: str
        """

        self._serial = serial

    @property
    def type(self):
        """Gets the type of this Device.  # noqa: E501


        :return: The type of this Device.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Device.


        :param type: The type of this Device.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def expires(self):
        """Gets the expires of this Device.  # noqa: E501


        :return: The expires of this Device.  # noqa: E501
        :rtype: datetime
        """
        return self._expires

    @expires.setter
    def expires(self, expires):
        """Sets the expires of this Device.


        :param expires: The expires of this Device.  # noqa: E501
        :type: datetime
        """

        self._expires = expires

    @property
    def last_connection(self):
        """Gets the last_connection of this Device.  # noqa: E501


        :return: The last_connection of this Device.  # noqa: E501
        :rtype: datetime
        """
        return self._last_connection

    @last_connection.setter
    def last_connection(self, last_connection):
        """Sets the last_connection of this Device.


        :param last_connection: The last_connection of this Device.  # noqa: E501
        :type: datetime
        """

        self._last_connection = last_connection

    @property
    def first_seen(self):
        """Gets the first_seen of this Device.  # noqa: E501


        :return: The first_seen of this Device.  # noqa: E501
        :rtype: datetime
        """
        return self._first_seen

    @first_seen.setter
    def first_seen(self, first_seen):
        """Sets the first_seen of this Device.


        :param first_seen: The first_seen of this Device.  # noqa: E501
        :type: datetime
        """
        if self._configuration.client_side_validation and first_seen is None:
            raise ValueError("Invalid value for `first_seen`, must not be `None`")  # noqa: E501

        self._first_seen = first_seen

    @property
    def mode(self):
        """Gets the mode of this Device.  # noqa: E501


        :return: The mode of this Device.  # noqa: E501
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this Device.


        :param mode: The mode of this Device.  # noqa: E501
        :type: str
        """

        self._mode = mode

    @property
    def name(self):
        """Gets the name of this Device.  # noqa: E501


        :return: The name of this Device.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Device.


        :param name: The name of this Device.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def battery_voltage(self):
        """Gets the battery_voltage of this Device.  # noqa: E501


        :return: The battery_voltage of this Device.  # noqa: E501
        :rtype: float
        """
        return self._battery_voltage

    @battery_voltage.setter
    def battery_voltage(self, battery_voltage):
        """Sets the battery_voltage of this Device.


        :param battery_voltage: The battery_voltage of this Device.  # noqa: E501
        :type: float
        """

        self._battery_voltage = battery_voltage

    @property
    def battery_pct(self):
        """Gets the battery_pct of this Device.  # noqa: E501


        :return: The battery_pct of this Device.  # noqa: E501
        :rtype: float
        """
        return self._battery_pct

    @battery_pct.setter
    def battery_pct(self, battery_pct):
        """Sets the battery_pct of this Device.


        :param battery_pct: The battery_pct of this Device.  # noqa: E501
        :type: float
        """

        self._battery_pct = battery_pct

    @property
    def battery_type(self):
        """Gets the battery_type of this Device.  # noqa: E501


        :return: The battery_type of this Device.  # noqa: E501
        :rtype: str
        """
        return self._battery_type

    @battery_type.setter
    def battery_type(self, battery_type):
        """Sets the battery_type of this Device.


        :param battery_type: The battery_type of this Device.  # noqa: E501
        :type: str
        """

        self._battery_type = battery_type

    @property
    def tags(self):
        """Gets the tags of this Device.  # noqa: E501


        :return: The tags of this Device.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this Device.


        :param tags: The tags of this Device.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    @property
    def current_mode(self):
        """Gets the current_mode of this Device.  # noqa: E501

        Indicates last known device state. 0 = awake, 1 = sleep, 6 = flight mode  # noqa: E501

        :return: The current_mode of this Device.  # noqa: E501
        :rtype: float
        """
        return self._current_mode

    @current_mode.setter
    def current_mode(self, current_mode):
        """Sets the current_mode of this Device.

        Indicates last known device state. 0 = awake, 1 = sleep, 6 = flight mode  # noqa: E501

        :param current_mode: The current_mode of this Device.  # noqa: E501
        :type: float
        """

        self._current_mode = current_mode

    @property
    def color(self):
        """Gets the color of this Device.  # noqa: E501


        :return: The color of this Device.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this Device.


        :param color: The color of this Device.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def save_to_web(self):
        """Gets the save_to_web of this Device.  # noqa: E501


        :return: The save_to_web of this Device.  # noqa: E501
        :rtype: bool
        """
        return self._save_to_web

    @save_to_web.setter
    def save_to_web(self, save_to_web):
        """Sets the save_to_web of this Device.


        :param save_to_web: The save_to_web of this Device.  # noqa: E501
        :type: bool
        """

        self._save_to_web = save_to_web

    @property
    def active(self):
        """Gets the active of this Device.  # noqa: E501


        :return: The active of this Device.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this Device.


        :param active: The active of this Device.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def deep_sleep(self):
        """Gets the deep_sleep of this Device.  # noqa: E501


        :return: The deep_sleep of this Device.  # noqa: E501
        :rtype: bool
        """
        return self._deep_sleep

    @deep_sleep.setter
    def deep_sleep(self, deep_sleep):
        """Sets the deep_sleep of this Device.


        :param deep_sleep: The deep_sleep of this Device.  # noqa: E501
        :type: bool
        """

        self._deep_sleep = deep_sleep

    @property
    def simstate(self):
        """Gets the simstate of this Device.  # noqa: E501


        :return: The simstate of this Device.  # noqa: E501
        :rtype: str
        """
        return self._simstate

    @simstate.setter
    def simstate(self, simstate):
        """Sets the simstate of this Device.


        :param simstate: The simstate of this Device.  # noqa: E501
        :type: str
        """

        self._simstate = simstate

    @property
    def stripe_subscription(self):
        """Gets the stripe_subscription of this Device.  # noqa: E501


        :return: The stripe_subscription of this Device.  # noqa: E501
        :rtype: str
        """
        return self._stripe_subscription

    @stripe_subscription.setter
    def stripe_subscription(self, stripe_subscription):
        """Sets the stripe_subscription of this Device.


        :param stripe_subscription: The stripe_subscription of this Device.  # noqa: E501
        :type: str
        """

        self._stripe_subscription = stripe_subscription

    @property
    def subscription_type(self):
        """Gets the subscription_type of this Device.  # noqa: E501


        :return: The subscription_type of this Device.  # noqa: E501
        :rtype: str
        """
        return self._subscription_type

    @subscription_type.setter
    def subscription_type(self, subscription_type):
        """Sets the subscription_type of this Device.


        :param subscription_type: The subscription_type of this Device.  # noqa: E501
        :type: str
        """

        self._subscription_type = subscription_type

    @property
    def meta(self):
        """Gets the meta of this Device.  # noqa: E501


        :return: The meta of this Device.  # noqa: E501
        :rtype: object
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """Sets the meta of this Device.


        :param meta: The meta of this Device.  # noqa: E501
        :type: object
        """

        self._meta = meta

    @property
    def reseller_id(self):
        """Gets the reseller_id of this Device.  # noqa: E501


        :return: The reseller_id of this Device.  # noqa: E501
        :rtype: float
        """
        return self._reseller_id

    @reseller_id.setter
    def reseller_id(self, reseller_id):
        """Sets the reseller_id of this Device.


        :param reseller_id: The reseller_id of this Device.  # noqa: E501
        :type: float
        """

        self._reseller_id = reseller_id

    @property
    def reseller_plan_id(self):
        """Gets the reseller_plan_id of this Device.  # noqa: E501


        :return: The reseller_plan_id of this Device.  # noqa: E501
        :rtype: float
        """
        return self._reseller_plan_id

    @reseller_plan_id.setter
    def reseller_plan_id(self, reseller_plan_id):
        """Sets the reseller_plan_id of this Device.


        :param reseller_plan_id: The reseller_plan_id of this Device.  # noqa: E501
        :type: float
        """

        self._reseller_plan_id = reseller_plan_id

    @property
    def bt_passkey(self):
        """Gets the bt_passkey of this Device.  # noqa: E501


        :return: The bt_passkey of this Device.  # noqa: E501
        :rtype: float
        """
        return self._bt_passkey

    @bt_passkey.setter
    def bt_passkey(self, bt_passkey):
        """Sets the bt_passkey of this Device.


        :param bt_passkey: The bt_passkey of this Device.  # noqa: E501
        :type: float
        """

        self._bt_passkey = bt_passkey

    @property
    def id(self):
        """Gets the id of this Device.  # noqa: E501


        :return: The id of this Device.  # noqa: E501
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Device.


        :param id: The id of this Device.  # noqa: E501
        :type: float
        """

        self._id = id

    @property
    def owner_id(self):
        """Gets the owner_id of this Device.  # noqa: E501


        :return: The owner_id of this Device.  # noqa: E501
        :rtype: float
        """
        return self._owner_id

    @owner_id.setter
    def owner_id(self, owner_id):
        """Sets the owner_id of this Device.


        :param owner_id: The owner_id of this Device.  # noqa: E501
        :type: float
        """

        self._owner_id = owner_id

    @property
    def secure_phone_id(self):
        """Gets the secure_phone_id of this Device.  # noqa: E501


        :return: The secure_phone_id of this Device.  # noqa: E501
        :rtype: float
        """
        return self._secure_phone_id

    @secure_phone_id.setter
    def secure_phone_id(self, secure_phone_id):
        """Sets the secure_phone_id of this Device.


        :param secure_phone_id: The secure_phone_id of this Device.  # noqa: E501
        :type: float
        """

        self._secure_phone_id = secure_phone_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Device, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Device):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Device):
            return True

        return self.to_dict() != other.to_dict()
